### ISSUE TITLE
Can you provides a english README

### ISSUE THREAD

**Issue by lucky-xiaohu** [humanscape/react-native-play-services#4]
This package is great, but most peoples(like me) don't understand the README language(look like Korean),
can you provides english README?

**Comment by humanscape-henry** [comment]
hello @lucky-xiaohu. Thanks for your interest.

we're sorry for the inconvenience about using react-native-play-services. translation is currently working on, so we'll quickly reply to you when it's completed.

**Comment by lucky-xiaohu** [comment]
thanks very much.

**Comment by humanscape-henry** [comment]
We have changed default documentation language to English for this repository. 😄 
See documentation at https://github.com/humanscape/react-native-play-services/blob/master/README.md
